### ISSUE TITLE
Please add support for static routes / port-channel interfaces (with vpc) / vpc domain config

### ISSUE THREAD

**Issue by mobig** [netascode/terraform-provider-nxos#134]
it would be extremally helpful if you could add the following to the provider:

- static routes (this currently can't be accomplished via the nxos_rest resource as two simultaneous calls are need, one for the destination prefix and another for the next-hop and it appears that the nxos_rest resource can only manage a single object at a time)
- port-channel configs
- vpc config (this would be a resource that lets you create the vpc domain and then an option on the ethernet interface to set the vpc number

**Comment by danischm** [comment]
v0.4.0 adds support for port-channels, vPCs and static routes.

**Comment by mobig** [comment]
thanks for getting this implemented
