### ISSUE TITLE
RSA key authentication

### ISSUE THREAD

**Issue by lemontree61089** [netascode/terraform-provider-nxos#44]
Hi,

Would it be possible to authenticate with an RSA key instead of a password?

**Comment by danischm** [comment]
I am not aware of any other NX-API REST authentication methods besides username/password. There is a possibility to configure a TLS server certificate on the device which could be verified on the client side.

**Comment by lemontree61089** [comment]
Hi,

You are right, I thought it was possible but after checking Cisco documentation, it looks like it is not at this time.
