### ISSUE TITLE
EVPN/VXLAN modules

### ISSUE THREAD

**Issue by lemontree61089** [netascode/terraform-provider-nxos#45]
Hello,

I am looking at this provider in order to deploy EVPN services on a Nexus VXLAN fabric. Services that I deploy are the classic ones:
-VLAN with L2VNI/BGP configuration
-VRF with L3VNI/BGP configuration

I was wondering if this could be part of modules to simplify it

**Comment by danischm** [comment]
Most of it should be there. Are you missing something specifically?

**Comment by lemontree61089** [comment]
Apologies, I somehow missed the modules in the documentation. I'll check if there is all I need, but yes it looks like pretty much everything is there
