### ISSUE TITLE
ACL changes cannot be validated by Terraform with NXOS provider

### ISSUE THREAD

**Issue by oldguardmd** [netascode/terraform-provider-nxos#66]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform: v1.2.3
netascode/nxos: 0.3.20

### Affected Resource(s)
- nxos_ipv4_access_list_entry

### Terraform Configuration Files
[https://github.com/netascode/terraform-nxos-acl-example/blob/main/main.tf](url)

### Expected Behavior
ACL should be created using the int16 value required by the API, but the response is a string in some cases, and the validation portion of the terraform apply needs to know to expect different string values. 

### Actual Behavior
The value gets properly set in the switch, but you get the following errors message because the validation cannot complete:
 Error: Incorrect attribute value type
```│
│   on main.tf line 69, in resource "nxos_ipv4_access_list_entry" "acl_entry":
│   69:   destination_port_1        = each.value.destination_port_1
│     ├────────────────
│     │ each.value.destination_port_1 is "domain"
│
│ Inappropriate value for attribute "destination_port_1": a number is required.
```

### Steps to Reproduce
1. `terraform apply`

### References
https://pubhub.devnetcloud.com/media/nxapi-dme-model-reference/docs/Security%20and%20Policing/ipv4acl:ACE/

The reference doesn't make clear that the the POST for changes requires unit16, but GET will return a string that changes the name to reference common protocols as listed in the above link.

**Comment by danischm** [comment]
https://github.com/netascode/terraform-provider-nxos/commit/1368f76421dcf39cc37151130ab9c9c3bc522040
