### ISSUE TITLE
New Resource: Add Spanning Tree Interface Resource for MO stpIf (sys/stp/inst/if-[<int>])

### ISSUE THREAD

**Issue by aj-cruz** [netascode/terraform-provider-nxos#89]
### Terraform Version
```
Terraform v1.2.7
on linux_amd64
+ provider registry.terraform.io/netascode/nxos v0.3.21
```
### Important Factoids
Not sure if this is covered under another resource, I couldn't find anything, but would like to be able to modify a port's Spanning Tree port type.

Proposed new resource: nxos_spanning_tree_interface
Proposed arguments:
- interface_id (string, Must match first field in the output of show intf brief. Example: eth1/1)
- port_type (string, one of: normal, network, edge, trunk)
- bpdufilter (string, one of: enable, disable)
- bpduguard (string, one of: enable, disable)
- guard (string, one of: none, loop, root)
- cost (string, auto or numerical range: 1-200000000)

### References

**Comment by danischm** [comment]
If you know them already could you maybe list the DME objects you would require?

**Comment by aj-cruz** [comment]
/sys/stp/inst/if-[interface]

**Comment by danischm** [comment]
Added in release 0.3.22.
